ci: add descriptive message for merge conflicts (#29215)
Fix #29199

PR Close #29215

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -73,7 +73,7 @@ var_7: &post_checkout
       if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
         # Fetch the head and merge commits for this PR.
         git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/head:pr/$CIRCLE_PR_NUMBER/head
-        git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/merge:pr/$CIRCLE_PR_NUMBER/merge
+        git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/merge:pr/$CIRCLE_PR_NUMBER/merge || (echo "Could not fetch merge result with master for this PR. Please check and fix any merge conflicts." ; exit 1)
         # Checkout the merged PR for testing as CircleCI will just use the PR head otherwise.
         git checkout -qf pr/$CIRCLE_PR_NUMBER/merge
         # Reset the merge commit into its PR head.
