build: suppress errors in git hooks
When errors occur in git hooks, we can safely supress them as they are validated on CI.

This is primarily coming up as an issue related to needing to reinstall node_modules

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,11 @@
 #!/bin/sh
 . "$(dirname $0)/_/husky.sh"
 
-yarn -s ng-dev format staged;
+set +e
+yarn -s ng-dev format staged 2>/dev/null
+if [ $? -ne 0 ]; then
+  echo "WARNING: failed to run pre-commit hook"
+fi
+
+
+exit 0;
