build: suppress errors in git hooks (#42484)
When errors occur in git hooks, we can safely supress them as they are validated on CI.

This is primarily coming up as an issue related to needing to reinstall node_modules

PR Close #42484

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -1,4 +1,11 @@
 #!/bin/sh
 . "$(dirname $0)/_/husky.sh"
 
-yarn -s ng-dev commit-message restore-commit-message-draft $1 $2;
+set +e
+
+yarn -s ng-dev commit-message restore-commit-message-draft $1 $2 2>/dev/null
+if [ $? -ne 0 ]; then
+  echo "WARNING: failed to attempt to restore commit message draft (ng-dev commit-message restore-commit-message-draft)"
+fi
+
+exit 0;
